<?xml version="1.0" ?>
<!DOCTYPE datafile [
<!ELEMENT datafile ANY>
	<!ELEMENT header ANY>
		<!ELEMENT emu_name (#PCDATA)>
		<!ELEMENT emu_parser (#PCDATA)>
		<!ELEMENT emu_description (#PCDATA)>
		<!ELEMENT emu_category (#PCDATA)>
		<!ELEMENT emu_version (#PCDATA)>
		<!ELEMENT emu_date (#PCDATA)>
		<!ELEMENT emu_author (#PCDATA)>
		<!ELEMENT emu_homepage (#PCDATA)>
		<!ELEMENT emu_baseurl (#PCDATA)>
		<!ELEMENT emu_launcher (#PCDATA)>
		<!ELEMENT emu_ext_launch_cmd (#PCDATA)>
		<!ELEMENT emu_downloadpath (#PCDATA)>
		<!ELEMENT emu_postdlaction (#PCDATA)>
		<!ELEMENT emu_comment (#PCDATA)>
		<!ELEMENT emu_thumb (#PCDATA)>
		<!ELEMENT emu_banner (#PCDATA)>
		<!ELEMENT emu_fanart (#PCDATA)>
		<!ELEMENT emu_logo (#PCDATA)>
		<!ELEMENT emu_trailer (#PCDATA)>
	<!ELEMENT game ANY>
		<!ATTLIST game name CDATA #REQUIRED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good|verified) "good">
		<!ELEMENT title_clean (#PCDATA)>
		<!ELEMENT plot (#PCDATA)>
		<!ELEMENT releasedate (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT genre (#PCDATA)>
		<!ELEMENT studio (#PCDATA)>
		<!ELEMENT nplayers (#PCDATA)>
		<!ELEMENT perspective (#PCDATA)>
		<!ELEMENT rating (#PCDATA)>
		<!ELEMENT ESRB (#PCDATA)>
		<!ELEMENT videoid (#PCDATA)>
		<!ELEMENT thegamesdb_id (#PCDATA)>
		<!ELEMENT gamefaqs_url (#PCDATA)>
		<!ELEMENT moby_url (#PCDATA)>
		<!ELEMENT consolegrid_url (#PCDATA)>
		<!ELEMENT boxart1 (#PCDATA)>
		<!ELEMENT boxart2 (#PCDATA)>
		<!ELEMENT boxart3 (#PCDATA)>
		<!ELEMENT boxart4 (#PCDATA)>
		<!ELEMENT boxart5 (#PCDATA)>
		<!ELEMENT boxart6 (#PCDATA)>
		<!ELEMENT boxart7 (#PCDATA)>
		<!ELEMENT boxart8 (#PCDATA)>
		<!ELEMENT boxart9 (#PCDATA)>
		<!ELEMENT boxart10 (#PCDATA)>
		<!ELEMENT snapshot1 (#PCDATA)>
		<!ELEMENT snapshot2 (#PCDATA)>
		<!ELEMENT snapshot3 (#PCDATA)>
		<!ELEMENT snapshot4 (#PCDATA)>
		<!ELEMENT snapshot5 (#PCDATA)>
		<!ELEMENT snapshot6 (#PCDATA)>
		<!ELEMENT snapshot7 (#PCDATA)>
		<!ELEMENT snapshot8 (#PCDATA)>
		<!ELEMENT snapshot9 (#PCDATA)>
		<!ELEMENT snapshot10 (#PCDATA)>		
		<!ELEMENT fanart1 (#PCDATA)>
		<!ELEMENT fanart2 (#PCDATA)>
		<!ELEMENT fanart3 (#PCDATA)>
		<!ELEMENT fanart4 (#PCDATA)>
		<!ELEMENT fanart5 (#PCDATA)>
		<!ELEMENT fanart6 (#PCDATA)>
		<!ELEMENT fanart7 (#PCDATA)>
		<!ELEMENT fanart8 (#PCDATA)>
		<!ELEMENT fanart9 (#PCDATA)>
		<!ELEMENT fanart10 (#PCDATA)>
		<!ELEMENT fanart11 (#PCDATA)>
		<!ELEMENT fanart12 (#PCDATA)>
		<!ELEMENT fanart13 (#PCDATA)>
		<!ELEMENT fanart14 (#PCDATA)>
		<!ELEMENT fanart15 (#PCDATA)>
		<!ELEMENT fanart16 (#PCDATA)>
		<!ELEMENT fanart17 (#PCDATA)>
		<!ELEMENT fanart18 (#PCDATA)>
		<!ELEMENT fanart19 (#PCDATA)>
		<!ELEMENT fanart20 (#PCDATA)>
		<!ELEMENT fanart21 (#PCDATA)>
		<!ELEMENT fanart22 (#PCDATA)>
		<!ELEMENT fanart23 (#PCDATA)>
		<!ELEMENT fanart24 (#PCDATA)>
		<!ELEMENT fanart25 (#PCDATA)>
		<!ELEMENT fanart26 (#PCDATA)>
		<!ELEMENT fanart27 (#PCDATA)>
		<!ELEMENT fanart28 (#PCDATA)>
		<!ELEMENT fanart29 (#PCDATA)>
		<!ELEMENT fanart30 (#PCDATA)>
		<!ELEMENT banner1 (#PCDATA)>
		<!ELEMENT banner2 (#PCDATA)>
		<!ELEMENT banner3 (#PCDATA)>
		<!ELEMENT banner4 (#PCDATA)>
		<!ELEMENT banner5 (#PCDATA)>
		<!ELEMENT banner6 (#PCDATA)>
		<!ELEMENT banner7 (#PCDATA)>
		<!ELEMENT banner8 (#PCDATA)>
		<!ELEMENT banner9 (#PCDATA)>
		<!ELEMENT banner10 (#PCDATA)>
		<!ELEMENT clearlogo1 (#PCDATA)>
		<!ELEMENT clearlogo2 (#PCDATA)>
		<!ELEMENT clearlogo3 (#PCDATA)>
		<!ELEMENT clearlogo4 (#PCDATA)>
		<!ELEMENT clearlogo5 (#PCDATA)>
		<!ELEMENT clearlogo6 (#PCDATA)>
		<!ELEMENT clearlogo7 (#PCDATA)>
		<!ELEMENT clearlogo8 (#PCDATA)>
		<!ELEMENT clearlogo9 (#PCDATA)>
		<!ELEMENT clearlogo10 (#PCDATA)>
]>
<datafile>
	<header>
		<emu_name>Quake</emu_name>
		<emu_parser>NoIntro_parser.xml</emu_parser>
		<emu_description>Quake</emu_description>
		<emu_category>ports</emu_category>
		<emu_version>20151220</emu_version>
		<emu_date>14/08/2016</emu_date>
		<emu_author>Lefty420</emu_author>
		<emu_homepage>http://www.no-intro.org</emu_homepage>
		<emu_baseurl>https://archive.org/download/</emu_baseurl>
		<emu_launcher>external</emu_launcher>
		<emu_ext_launch_cmd>/usr/bin/retroarch.sh %NETPLAY_COMMAND% -L /tmp/cores/tyrquake_libretro.so "%ROM_PATH%"</emu_ext_launch_cmd>
		<emu_downloadpath>default</emu_downloadpath>
		<emu_postdlaction>unzip_rom</emu_postdlaction>
		<emu_comment>Quake Retroarch port, provided by Lefty420.</emu_comment>
			<emu_thumb>http://i.imgur.com/yx17By8.jpg</emu_thumb>
			<emu_banner>http://i.imgur.com/171sMlm.jpg</emu_banner>
			<emu_fanart>http://i.imgur.com/jsk2VsS.jpg</emu_fanart>
			<emu_logo>http://i.imgur.com/GS0FJZS.png</emu_logo>
			<emu_trailer>5WzyVjx-SXM</emu_trailer>
		</header>
			<game name="Quake">
				<description>Quake</description>
				<rom name="tom_bftp_D/id1.zip" size="1688202" />
				<title_clean>quake</title_clean>
				<plot>Quake is a first-person shooter video game, developed by id Software and published by GT Interactive in 1996. It features music composed by Trent Reznor and Nine Inch Nails.[CR]It is the first game in the Quake series. In the game, players must find their way through various maze-like, medieval environments while battling a variety of monsters using a wide array of weapons.[CR]The successor to id Software's Doom series, Quake built upon the technology and gameplay of its predecessor. Unlike the Doom engine before it, the Quake engine offered full real-time 3D rendering and had early support for 3D acceleration through OpenGL. After Doom helped popularize multiplayer deathmatches, Quake added various multiplayer options. Online multiplayer became increasingly common, with the QuakeWorld update and software such as QuakeSpy making the process of finding and playing against others on the Internet easier and more reliable.[CR]Programmer Michael Abrash had stated in a 2013 interview that Quake is his favourite game "of all time."</plot>
				<releasedate>22/06/1996</releasedate>
				<year>1999</year>
				<genre>FPS</genre>
				<nplayers>1</nplayers>
				<thegamesdb_id>777</thegamesdb_id>
				<videoid>5WzyVjx-SXM</videoid>
				<giantbomb_url>http://www.giantbomb.com/quake/3030-8015/</giantbomb_url>
				<boxart1>http://thegamesdb.net/banners/_gameviewcache/boxart/original/front/777-1.jpg</boxart1>
				<banner1>https://s29.postimg.io/gxxvrm8nr/Quake.png</banner1>
			</game>
</datafile>
			
			