<!DOCTYPE datafile [
<!ELEMENT datafile ANY>
	<!ELEMENT header ANY>
		<!ELEMENT emu_name (#PCDATA)>
		<!ELEMENT emu_parser (#PCDATA)>
		<!ELEMENT emu_description (#PCDATA)>
		<!ELEMENT emu_category (#PCDATA)>
		<!ELEMENT emu_version (#PCDATA)>
		<!ELEMENT emu_date (#PCDATA)>
		<!ELEMENT emu_author (#PCDATA)>
		<!ELEMENT emu_homepage (#PCDATA)>
		<!ELEMENT emu_baseurl (#PCDATA)>
		<!ELEMENT emu_launcher (#PCDATA)>
		<!ELEMENT emu_ext_launch_cmd (#PCDATA)>
		<!ELEMENT emu_downloadpath (#PCDATA)>
		<!ELEMENT emu_postdlaction (#PCDATA)>
		<!ELEMENT emu_comment (#PCDATA)>
		<!ELEMENT emu_thumb (#PCDATA)>
		<!ELEMENT emu_banner (#PCDATA)>
		<!ELEMENT emu_fanart (#PCDATA)>
		<!ELEMENT emu_logo (#PCDATA)>
		<!ELEMENT emu_trailer (#PCDATA)>
	<!ELEMENT game ANY>
		<!ATTLIST game name CDATA #REQUIRED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good|verified) "good">
		<!ELEMENT emu_command (#PCDATA)>
		<!ELEMENT videoid (#PCDATA)>
		<!ELEMENT plot (#PCDATA)>
		<!ELEMENT genre (#PCDATA)>
		<!ELEMENT nplayers (#PCDATA)>
		<!ELEMENT studio (#PCDATA)>
		<!ELEMENT releasedate (#PCDATA)>
		<!ELEMENT fanart1 (#PCDATA)>
		<!ELEMENT fanart2 (#PCDATA)>
		<!ELEMENT fanart3 (#PCDATA)>
		<!ELEMENT fanart4 (#PCDATA)>
		<!ELEMENT fanart5 (#PCDATA)>
		<!ELEMENT fanart6 (#PCDATA)>
		<!ELEMENT fanart7 (#PCDATA)>
		<!ELEMENT fanart8 (#PCDATA)>
		<!ELEMENT fanart9 (#PCDATA)>
		<!ELEMENT fanart10 (#PCDATA)>
		<!ELEMENT fanart11 (#PCDATA)>
		<!ELEMENT fanart12 (#PCDATA)>
		<!ELEMENT fanart13 (#PCDATA)>
		<!ELEMENT fanart14 (#PCDATA)>
		<!ELEMENT fanart15 (#PCDATA)>
		<!ELEMENT fanart16 (#PCDATA)>
		<!ELEMENT fanart17 (#PCDATA)>
		<!ELEMENT fanart18 (#PCDATA)>
		<!ELEMENT fanart19 (#PCDATA)>
		<!ELEMENT fanart20 (#PCDATA)>
		<!ELEMENT fanart21 (#PCDATA)>
		<!ELEMENT fanart22 (#PCDATA)>
		<!ELEMENT fanart23 (#PCDATA)>
		<!ELEMENT fanart24 (#PCDATA)>
		<!ELEMENT fanart25 (#PCDATA)>
		<!ELEMENT fanart26 (#PCDATA)>
		<!ELEMENT fanart27 (#PCDATA)>
		<!ELEMENT fanart28 (#PCDATA)>
		<!ELEMENT fanart29 (#PCDATA)>
		<!ELEMENT fanart30 (#PCDATA)>
		<!ELEMENT boxart1 (#PCDATA)>
		<!ELEMENT boxart2 (#PCDATA)>
		<!ELEMENT boxart3 (#PCDATA)>
		<!ELEMENT boxart4 (#PCDATA)>
		<!ELEMENT boxart5 (#PCDATA)>
		<!ELEMENT boxart6 (#PCDATA)>
		<!ELEMENT boxart7 (#PCDATA)>
		<!ELEMENT boxart8 (#PCDATA)>
		<!ELEMENT boxart9 (#PCDATA)>
		<!ELEMENT boxart10 (#PCDATA)>
		<!ELEMENT snapshot1 (#PCDATA)>
		<!ELEMENT snapshot2 (#PCDATA)>
		<!ELEMENT snapshot3 (#PCDATA)>
		<!ELEMENT snapshot4 (#PCDATA)>
		<!ELEMENT snapshot5 (#PCDATA)>
		<!ELEMENT snapshot6 (#PCDATA)>
		<!ELEMENT snapshot7 (#PCDATA)>
		<!ELEMENT snapshot8 (#PCDATA)>
		<!ELEMENT snapshot9 (#PCDATA)>
		<!ELEMENT snapshot10 (#PCDATA)>
		<!ELEMENT banner1 (#PCDATA)>
		<!ELEMENT banner2 (#PCDATA)>
		<!ELEMENT banner3 (#PCDATA)>
		<!ELEMENT banner4 (#PCDATA)>
		<!ELEMENT banner5 (#PCDATA)>
		<!ELEMENT banner6 (#PCDATA)>
		<!ELEMENT banner7 (#PCDATA)>
		<!ELEMENT banner8 (#PCDATA)>
		<!ELEMENT banner9 (#PCDATA)>
		<!ELEMENT banner10 (#PCDATA)>
		<!ELEMENT clearlogo1 (#PCDATA)>
		<!ELEMENT clearlogo2 (#PCDATA)>
		<!ELEMENT clearlogo3 (#PCDATA)>
		<!ELEMENT clearlogo4 (#PCDATA)>
		<!ELEMENT clearlogo5 (#PCDATA)>
		<!ELEMENT clearlogo6 (#PCDATA)>
		<!ELEMENT clearlogo7 (#PCDATA)>
		<!ELEMENT clearlogo8 (#PCDATA)>
		<!ELEMENT clearlogo9 (#PCDATA)>
		<!ELEMENT clearlogo10 (#PCDATA)>
]>
	<datafile>
		<header>
			<emu_name>Internet Archive Best Of - Sierra and LucasArts</emu_name>
			<emu_parser>NoIntro_parser.xml</emu_parser>
			<emu_description>Best_of_Point_and_Click</emu_description>
			<emu_category>Top 50</emu_category>
			<emu_version>20151219</emu_version>
			<emu_date>12/19/2015</emu_date>
			<emu_author>Zach_Morris</emu_author>
			<emu_homepage>http://www.no-intro.org</emu_homepage>
			<emu_baseurl>http://archive.org/download/</emu_baseurl>
			<emu_launcher>external</emu_launcher>
			<emu_ext_launch_cmd>/usr/bin/retroarch.sh %NETPLAY_COMMAND% -L /tmp/cores/dosbox_libretro.so "%ROM_PATH%"</emu_ext_launch_cmd>
			<emu_downloadpath>default</emu_downloadpath>
			<emu_postdlaction>unzip_dosbox_update_conf_file</emu_postdlaction>
			<emu_comment>Whether you were a fan of Sierra and LucasArts's fantastic point-and-click adventures or its remarkable licensed games, there's a good chance you have fond, nostalgic memories of the projects they spawned.  Though the companies have shut down, their legacy will live on in the developers it inspired to make their own games, to create their own worlds, and to tell their own stories.[CR]This collection honors Sierra and LucasArts' development legacy.</emu_comment>
			<emu_thumb>special://home/addons/plugin.program.iarl/resources/skins/Default/media/bestof_Sierra_LucasArts.png</emu_thumb>
			<emu_banner>special://home/addons/plugin.program.iarl/resources/skins/Default/media/bestof_Sierra_LucasArts_banner.jpg</emu_banner>
			<emu_fanart>http://i.imgur.com/HAENC3o.jpg</emu_fanart>
			<emu_logo>https://upload.wikimedia.org/wikipedia/commons/d/dd/DOSBox_icon.png</emu_logo>
			<emu_trailer>7iM9ljabZ-E</emu_trailer>
		</header>
			<game name="Adventures of Willy Beamish, The (1991)">
				<description>Adventures of Willy Beamish, The (1991)</description>
				<rom name="eXoDOSADV.v.2.0/eXoDOS-adventure.v2.0.zip/eXoDOS-Adventure%2FGames%2FAdventures%20of%20Willy%20Beamish%2C%20The%20%281991%29.zip" size="255378766" />
				<title_clean>Adventures of Willy Beamish, The</title_clean>
				<plot>Willy Beamish is a kid who likes to goof off and have fun. Naturally all the grown-ups get in the way by making him go to school, making him clean his room, etc. But now that's school's out for the summer, Willy is determined to have a good time and maybe even have his pet frog win the frog jumping contest. However Willy has a habit of getting into trouble, and naturally that means it will be a challenge to get out of it.[CR]The Adventures of Willy Beamish is a point-and-click graphical adventure. You play Willy Beamish, an eight year-old kid who is just trying to get through life without losing his lunch money. But he'll have to deal with parents, teachers, babysitters and bratty sisters. The player must solve different puzzles to ensure Willy can progress, get out of trouble and generally avoid ending up grounded. [CR]The in-game time progresses even if no action is taken. This means many puzzles have to be solved in a certain time frame or rely on being in the right place at the right time. A special aspect of this game is a bar which shows Willy's relationship to his parents. It gets affected by the way certain situations are resolved, e.g. it increases if Willy refuses to play with his sister, and when it is full they send Willy to a military school and the game is lost.</plot>
				<releasedate>1/1/1991</releasedate>
				<year>1991</year>
				<genre>Adventure</genre>
				<studio>Sierra On-Line, Inc.</studio>
				<nplayers>1</nplayers>
				<perspective>3rd-Person</perspective>
				<rating>3.9</rating>
				<thegamesdb_id>3662</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/dos/adventures-of-willy-beamish</mobygames_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/3662-1.jpg</boxart1>
				<boxart2>http://thegamesdb.net/banners/boxart/original/back/3662-1.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/80883-the-adventures-of-willy-beamish-dos-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/110812-the-adventures-of-willy-beamish-dos-media.jpg</boxart4>
				<boxart5>http://www.mobygames.com/images/covers/l/110814-the-adventures-of-willy-beamish-dos-media.jpg</boxart5>
				<boxart6>http://www.mobygames.com/images/covers/l/202157-the-adventures-of-willy-beamish-dos-media.jpg</boxart6>
				<snapshot1>http://www.mobygames.com/images/shots/l/11783-the-adventures-of-willy-beamish-dos-screenshot-title-screen.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/119145-the-adventures-of-willy-beamish-dos-screenshot-title-screen.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/11784-the-adventures-of-willy-beamish-dos-screenshot-headmaster-mr.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/11785-the-adventures-of-willy-beamish-dos-screenshot-everyone-gets.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/11786-the-adventures-of-willy-beamish-dos-screenshot-willy-dreaming.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/11787-the-adventures-of-willy-beamish-dos-screenshot-last-day-of.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/11788-the-adventures-of-willy-beamish-dos-screenshot-inside-willy.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/11789-the-adventures-of-willy-beamish-dos-screenshot-at-last-school.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/11790-the-adventures-of-willy-beamish-dos-screenshot-willy-s-neighborhood.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/11791-the-adventures-of-willy-beamish-dos-screenshot-in-front-of.jpg</snapshot10>
				<fanart1>http://thegamesdb.net/banners/fanart/original/3662-1.jpg</fanart1>
			</game>
			<game name="Betrayal at Krondor (1993)">
				<description>Betrayal at Krondor (1993)</description>
				<rom name="eXoDOSADV.v.2.0/eXoDOS-adventure.v2.0.zip/eXoDOS-Adventure%2FGames%2FBetrayal%20at%20Krondor%20%281993%29.zip" size="523394452" />
				<title_clean>Betrayal at Krondor</title_clean>
				<plot>Based on Raymond E. Feist's Riftwar saga (and co-written with Feist himself) is Betrayal At Krondor, a new tale in the Riftwar universe. [CR]The story begins as Gorath, a moredhel (dark elf) renegade, who intended to warn the people of Krondor of the upcoming moredhel invasion, is attacked by an assassin. Locklear, a nobleman who serves the crown of Krondor, and a young magician named Owyn decide to accompany Gorath to Krondor, where they'll have to think of a plan to stop the moredhel leader Delekhan.[CR]Exploration in a 3D world and turn-based combat complement the story, which is divided up into nine chapters.  Each chapter has a goal to achieve before moving on to the next chapter, but how that goal is met is up to you.</plot>
				<releasedate>31/7/1997</releasedate>
				<year>1993</year>
				<genre>Adventure, RPG</genre>
				<studio>Sierra On-Line, Inc.</studio>
				<perspective>1st-Person</perspective>
				<rating>3.9</rating>
				<thegamesdb_id>14021</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/dos/betrayal-at-krondor</mobygames_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/14021-1.jpg</boxart1>
				<boxart2>http://thegamesdb.net/banners/boxart/original/back/14021-1.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/108539-betrayal-at-krondor-dos-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/187808-betrayal-at-krondor-dos-media.jpg</boxart4>
				<boxart5>http://www.mobygames.com/images/covers/l/133276-betrayal-at-krondor-dos-media.jpg</boxart5>
				<boxart6>http://www.mobygames.com/images/covers/l/38082-betrayal-at-krondor-dos-media.jpg</boxart6>
				<boxart7>http://www.mobygames.com/images/covers/l/249321-betrayal-at-krondor-dos-media.jpg</boxart7>
				<boxart8>http://www.mobygames.com/images/covers/l/277109-betrayal-at-krondor-dos-media.jpg</boxart8>
				<boxart9>http://www.mobygames.com/images/covers/l/294868-betrayal-at-krondor-dos-media.jpg</boxart9>
				<snapshot1>http://www.mobygames.com/images/shots/l/1237-betrayal-at-krondor-dos-screenshot-title-screen.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/1242-betrayal-at-krondor-dos-screenshot-list-of-chapters.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/1238-betrayal-at-krondor-dos-screenshot-each-chapter-begins-with.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/1239-betrayal-at-krondor-dos-screenshot-intro-cutscene.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/1240-betrayal-at-krondor-dos-screenshot-introducing-gorath-a-moredhel.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/13528-betrayal-at-krondor-dos-screenshot-the-goal-is-to-protect-the.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/1243-betrayal-at-krondor-dos-screenshot-map-of-the-land.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/1241-betrayal-at-krondor-dos-screenshot-traversing-the-countryside.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/13531-betrayal-at-krondor-dos-screenshot-casting-lightning-on-an.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/13530-betrayal-at-krondor-dos-screenshot-winter-scene-with-a-catapult.jpg</snapshot10>
			</game>
			<game name="Black Cauldron, The (1986)">
				<description>Black Cauldron, The (1986)</description>
				<rom name="eXoDOSADV.v.2.0/eXoDOS-adventure.v2.0.zip/eXoDOS-Adventure%2FGames%2FBlack%20Cauldron%2C%20The%20%281986%29.zip" size="325098" />
				<title_clean>Black Cauldron, The</title_clean>
				<plot>Based on the Disney movie of the same name, The Black Cauldron focuses on the story of Taran, who is an assistant Pig-keeper in the land of Caer Dalben. One day Taran notices that one of his pigs, Hen Wen has magical powers. The Evil Horned King wants the pig so that he can locate the Black Cauldron and ultimately rule the world. Taran must now embark on a mission to rescue Hen Wen and defeat the Evil Horned King before his can discover the Cauldron's location.[CR]The Black Cauldron is a side-view adventure game. Gameplay is similar to other Sierra adventure games of its day (such as Space Quest II or King's Quest III) but does not use a text parser. Instead the function keys are used to initiate actions. Players control Taran and can make him walk, run, swim and interact (talk) with other characters in the game. Puzzle-solving and advancement in the plot requires item manipulation of using the right item at the right time or at the right location.</plot>
				<releasedate>1/7/1986</releasedate>
				<year>1986</year>
				<genre>Adventure</genre>
				<studio>Sierra On-Line, Inc.</studio>
				<nplayers>1</nplayers>
				<perspective>3rd-Person</perspective>
				<rating>3.5</rating>
				<thegamesdb_id>10825</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/dos/black-cauldron</mobygames_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/10825-1.jpg</boxart1>
				<boxart2>http://thegamesdb.net/banners/boxart/original/back/10825-1.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/238639-the-black-cauldron-dos-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/238641-the-black-cauldron-dos-media.jpg</boxart4>
				<boxart5>http://www.mobygames.com/images/covers/l/109545-the-black-cauldron-dos-media.jpg</boxart5>
				<boxart6>http://www.mobygames.com/images/covers/l/109546-the-black-cauldron-dos-media.jpg</boxart6>
				<boxart7>http://www.mobygames.com/images/covers/l/210135-the-black-cauldron-dos-media.jpg</boxart7>
				<boxart8>http://www.mobygames.com/images/covers/l/210136-the-black-cauldron-dos-media.jpg</boxart8>
				<boxart9>http://www.mobygames.com/images/covers/l/210137-the-black-cauldron-dos-media.jpg</boxart9>
				<boxart10>http://www.mobygames.com/images/covers/l/248663-the-black-cauldron-dos-media.jpg</boxart10>
				<snapshot1>http://www.mobygames.com/images/shots/l/803-the-black-cauldron-dos-screenshot-title-screen.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/804-the-black-cauldron-dos-screenshot-caer-dallben.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/805-the-black-cauldron-dos-screenshot-the-pig-keeper.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/806-the-black-cauldron-dos-screenshot-the-goat-thinks-you-want-to.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/807-the-black-cauldron-dos-screenshot-the-beautiful-woods-of-caer.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/808-the-black-cauldron-dos-screenshot-the-lake-of-caer-dallben.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/18374-the-black-cauldron-dos-screenshot-every-now-and-then-you-need.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/18375-the-black-cauldron-dos-screenshot-this-game-has-no-parser-you.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/18376-the-black-cauldron-dos-screenshot-the-castle-of-the-horned.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/18377-the-black-cauldron-dos-screenshot-action-sequence-swim-past.jpg</snapshot10>
				<clearlogo1>http://thegamesdb.net/banners/clearlogo/10825.png</clearlogo1>
			</game>
			<game name="Castle of Dr. Brain (1991)">
				<description>Castle of Dr. Brain (1991)</description>
				<rom name="eXoDOSADV.v.2.0/eXoDOS-adventure.v2.0.zip/eXoDOS-Adventure%2FGames%2FCastle%20of%20Dr.%20Brain%20%281991%29.zip" size="2562219" />
				<title_clean>Castle of Dr. Brain</title_clean>
				<plot>Castle of Dr. Brain is the first in a two-part series of educational puzzle-games from Sierra. This brain-blasting game is set, how surprisingly, in Dr. Brain's castle, where the player will have to beat Dr. Brain's traps and puzzles in order to fulfill the assignment given.</plot>
				<releasedate>1/1/1991</releasedate>
				<year>1991</year>
				<genre>Adventure, Educational</genre>
				<studio>Sierra On-Line, Inc.</studio>
				<perspective>1st-Person</perspective>
				<rating>4.1</rating>
				<ESRB>E - Everyone</ESRB>
				<thegamesdb_id>14690</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/dos/castle-of-dr-brain</mobygames_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/14690-1.jpg</boxart1>
				<boxart2>http://www.mobygames.com/images/covers/l/62015-castle-of-dr-brain-dos-back-cover.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/34290-castle-of-dr-brain-dos-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/108542-castle-of-dr-brain-dos-media.jpg</boxart4>
				<boxart5>http://www.mobygames.com/images/covers/l/300012-castle-of-dr-brain-dos-media.jpg</boxart5>
				<snapshot1>http://www.mobygames.com/images/shots/l/6740-castle-of-dr-brain-dos-screenshot-the-famous-sierra-logo.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/6741-castle-of-dr-brain-dos-screenshot-title-screen.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/6742-castle-of-dr-brain-dos-screenshot-first-screen.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/6743-castle-of-dr-brain-dos-screenshot-math-puzzle.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/6744-castle-of-dr-brain-dos-screenshot-the-castle-entrance.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/6745-castle-of-dr-brain-dos-screenshot-shape-matching-puzzle.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/6748-castle-of-dr-brain-dos-screenshot-math-puzzle.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/6749-castle-of-dr-brain-dos-screenshot-the-clock-room.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/359002-castle-of-dr-brain-dos-screenshot-the-first-elevator-maze.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/359003-castle-of-dr-brain-dos-screenshot-the-second-floor-hallway.jpg</snapshot10>
				<clearlogo1>http://thegamesdb.net/banners/clearlogo/14690.png</clearlogo1>
			</game>
			<game name="Codename ICEMAN (1989)">
				<description>Codename ICEMAN (1989)</description>
				<rom name="eXoDOSADV.v.2.0/eXoDOS-adventure.v2.0.zip/eXoDOS-Adventure%2FGames%2FCodename%20ICEMAN%20%281989%29.zip" size="2458289" />
				<title_clean>Codename ICEMAN</title_clean>
				<plot>Written by Jim Walls, Codename: ICEMAN was to be the first game in a new adventure game series by Sierra. A sequel was never released, although it was mentioned in Sierra's news magazine. You control Navy officer Johnny Westland, as he takes on a secret mission dealing with the oil reserves in Tunisia. The game is a traditional adventure, with interesting James Bond-esque spy elements. A large portion of the game is also played in a (perhaps overly complex for some players) submarine simulator.</plot>
				<releasedate>28/12/1989</releasedate>
				<year>1989</year>
				<genre>Adventure, Simulation</genre>
				<studio>Sierra On-Line, Inc.</studio>
				<perspective>3rd-Person</perspective>
				<rating>3.4</rating>
				<thegamesdb_id>14722</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/dos/code-name-iceman</mobygames_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/14722-1.jpg</boxart1>
				<boxart2>http://www.mobygames.com/images/covers/l/775-code-name-iceman-dos-back-cover.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/14592-code-name-iceman-dos-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/27050-code-name-iceman-dos-media.jpg</boxart4>
				<boxart5>http://www.mobygames.com/images/covers/l/246064-code-name-iceman-dos-media.jpg</boxart5>
				<boxart6>http://www.mobygames.com/images/covers/l/314230-code-name-iceman-dos-media.jpg</boxart6>
				<boxart7>http://www.mobygames.com/images/covers/l/314231-code-name-iceman-dos-media.jpg</boxart7>
				<boxart8>http://www.mobygames.com/images/covers/l/314232-code-name-iceman-dos-media.jpg</boxart8>
				<boxart9>http://www.mobygames.com/images/covers/l/314233-code-name-iceman-dos-media.jpg</boxart9>
				<boxart10>http://www.mobygames.com/images/covers/l/314234-code-name-iceman-dos-media.jpg</boxart10>
				<snapshot1>http://www.mobygames.com/images/shots/l/1970-code-name-iceman-dos-screenshot-title-screen.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/1971-code-name-iceman-dos-screenshot-credits.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/1972-code-name-iceman-dos-screenshot-intro.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/1973-code-name-iceman-dos-screenshot-first-screen.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/1974-code-name-iceman-dos-screenshot-playing-ball.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/1975-code-name-iceman-dos-screenshot-entering-the-lobby.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/1977-code-name-iceman-dos-screenshot-the-desk-clerk.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/1978-code-name-iceman-dos-screenshot-a-woman-in-the-bar.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/1979-code-name-iceman-dos-screenshot-shakin-yo-tail-feathers.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/254157-code-name-iceman-dos-screenshot-a-cut-scene-aboard-an-airplane.jpg</snapshot10>
				<clearlogo1>http://thegamesdb.net/banners/clearlogo/14722.png</clearlogo1>
			</game>
			<game name="Conquests of Camelot - The Search for the Grail (1990)">
				<description>Conquests of Camelot - The Search for the Grail (1990)</description>
				<rom name="eXoDOSADV.v.2.0/eXoDOS-adventure.v2.0.zip/eXoDOS-Adventure%2FGames%2FConquests%20of%20Camelot%20-%20The%20Search%20for%20the%20Grail%20%281990%29.zip" size="2818003" />
				<title_clean>Conquests of Camelot - The Search for the Grail</title_clean>
				<plot>Sierra graphic adventure game from the 16-color era.  Guide King Arthur as he searches for the Holy Grail in Britainnia and the Holy Land.   Merlin's spirit is an ever-present guide as Arthur travels throughout Britainnia, and to Gaza and Jersulem.  Along the way, Arthur will meet Gwynhyver, the Black Knight, and the Lady of the Lake, and he'll rescue Sir Launcelot and Sir Gawaine from danger.  Finally, he must pass the tests of the six goddesses to prove his worth and receive the Grail.</plot>
				<releasedate>1/1/1990</releasedate>
				<year>1990</year>
				<genre>Adventure</genre>
				<studio>Sierra On-Line, Inc.</studio>
				<perspective>3rd-Person</perspective>
				<rating>3.8</rating>
				<thegamesdb_id>14098</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/dos/conquests-of-camelot-the-search-for-the-grail</mobygames_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/14098-1.jpg</boxart1>
				<boxart2>http://thegamesdb.net/banners/boxart/original/back/14098-1.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/35773-conquests-of-camelot-the-search-for-the-grail-dos-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/235767-conquests-of-camelot-the-search-for-the-grail-dos-media.jpg</boxart4>
				<boxart5>http://www.mobygames.com/images/covers/l/89071-conquests-of-camelot-the-search-for-the-grail-dos-media.jpg</boxart5>
				<boxart6>http://www.mobygames.com/images/covers/l/89072-conquests-of-camelot-the-search-for-the-grail-dos-media.jpg</boxart6>
				<boxart7>http://www.mobygames.com/images/covers/l/26947-conquests-of-camelot-the-search-for-the-grail-dos-media.jpg</boxart7>
				<snapshot1>http://www.mobygames.com/images/shots/l/6241-conquests-of-camelot-the-search-for-the-grail-dos-screenshot.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/6242-conquests-of-camelot-the-search-for-the-grail-dos-screenshot.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/6244-conquests-of-camelot-the-search-for-the-grail-dos-screenshot.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/6245-conquests-of-camelot-the-search-for-the-grail-dos-screenshot.jpg</snapshot4>
				<snapshot5>http://www.mobygames.com/images/shots/l/700722-conquests-of-camelot-the-search-for-the-grail-dos-screenshot.jpg</snapshot5>
				<snapshot6>http://www.mobygames.com/images/shots/l/700723-conquests-of-camelot-the-search-for-the-grail-dos-screenshot.jpg</snapshot6>
				<snapshot7>http://www.mobygames.com/images/shots/l/359565-conquests-of-camelot-the-search-for-the-grail-dos-screenshot.jpg</snapshot7>
				<snapshot8>http://www.mobygames.com/images/shots/l/6248-conquests-of-camelot-the-search-for-the-grail-dos-screenshot.jpg</snapshot8>
				<snapshot9>http://www.mobygames.com/images/shots/l/6247-conquests-of-camelot-the-search-for-the-grail-dos-screenshot.jpg</snapshot9>
				<snapshot10>http://www.mobygames.com/images/shots/l/700724-conquests-of-camelot-the-search-for-the-grail-dos-screenshot.jpg</snapshot10>
				<clearlogo1>http://thegamesdb.net/banners/clearlogo/14098.png</clearlogo1>
			</game>
			<game name="Conquests of the Longbow - The Legend of Robin Hood (1991)">
				<description>Conquests of the Longbow - The Legend of Robin Hood (1991)</description>
				<rom name="eXoDOSADV.v.2.0/eXoDOS-adventure.v2.0.zip/eXoDOS-Adventure%2FGames%2FConquests%20of%20the%20Longbow%20-%20The%20Legend%20of%20Robin%20Hood%20%281991%29.zip" size="7261076" />
				<title_clean>Conquests of the Longbow - The Legend of Robin Hood</title_clean>
				<plot>This game is set in medieval England.  You play as Robin Hood.  Your objective is to free King Richard from the French by raising money for his ransome.  There are many different endings depending on the score you get.  The game uses a mouse interface.  There are arcade sequences built into the story, but their difficulty can be adjusted, or they can be completely turned off.</plot>
				<releasedate>1/1/1991</releasedate>
				<year>1991</year>
				<genre>Adventure</genre>
				<studio>Sierra On-Line, Inc.</studio>
				<perspective>3rd-Person</perspective>
				<rating>4.0</rating>
				<thegamesdb_id>14099</thegamesdb_id>
				<mobygames_url>http://www.mobygames.com/game/dos/conquests-of-the-longbow-the-legend-of-robin-hood</mobygames_url>
				<boxart1>http://thegamesdb.net/banners/boxart/original/front/14099-1.jpg</boxart1>
				<boxart2>http://thegamesdb.net/banners/boxart/original/back/14099-1.jpg</boxart2>
				<boxart3>http://www.mobygames.com/images/covers/l/110239-conquests-of-the-longbow-the-legend-of-robin-hood-dos-media.jpg</boxart3>
				<boxart4>http://www.mobygames.com/images/covers/l/95035-conquests-of-the-longbow-the-legend-of-robin-hood-dos-media.jpg</boxart4>
				<boxart5>http://www.mobygames.com/images/covers/l/146804-conquests-of-the-longbow-the-legend-of-robin-hood-dos-media.jpg</boxart5>
				<boxart6>http://www.mobygames.com/images/covers/l/291656-conquests-of-the-longbow-the-legend-of-robin-hood-dos-media.jpg</boxart6>
				<boxart7>http://www.mobygames.com/images/covers/l/291657-conquests-of-the-longbow-the-legend-of-robin-hood-dos-media.jpg</boxart7>
				<boxart8>http://www.mobygames.com/images/covers/l/253475-conquests-of-the-longbow-the-legend-of-robin-hood-dos-media.jpg</boxart8>
				<boxart9>http://www.mobygames.com/images/covers/l/253476-conquests-of-the-longbow-the-legend-of-robin-hood-dos-media.jpg</boxart9>
				<snapshot1>http://www.mobygames.com/images/shots/l/163118-conquests-of-the-longbow-the-legend-of-robin-hood-dos-screenshot.jpg</snapshot1>
				<snapshot2>http://www.mobygames.com/images/shots/l/163119-conquests-of-the-longbow-the-legend-of-robin-hood-dos-screenshot.jpg</snapshot2>
				<snapshot3>http://www.mobygames.com/images/shots/l/163121-conquests-of-the-longbow-the-legend-of-robin-hood-dos-screenshot.jpg</snapshot3>
				<snapshot4>http://www.mobygames.com/images/shots/l/163122-conquests-of-the-longbow-the-legend-of-robin-hood-dos-screenshot.jpg</snapshot4>